spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    # Тип кэша
    type: redis
    # Имя кэша
    cache-names: redis-cache
  data:
    redis:
      # Redis будет работать на локальной машине
      host: ${REDIS_HOST}
      # Стандартный порт
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    # Файл конфигурации Liquibase расположен по следующему пути
    change-log: classpath:liquibase/db.changelog.yaml
    # Сообщаем приложению, что Liquibase будет работать
    enabled: true
    # Данные будут сохранены в эту схему
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 3600000
    refresh: 2592000000
springdoc:
  # Отключаем отображение излишних ошибок (403, 404 и др.)
  override-with-generic-response: false
