spring:
  cache:
    # Тип кэша
    type: redis
    # Имя кэша
    cache-names: redis-cache
  data:
    redis:
      # Redis будет работать на локальной машине
      host: localhost
      # Стандартный порт
      port: 6379
      password: YXNoZGtkYWxkc2QnZHc=
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: mikhail
    password: qT4d32
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  #      data-locations: classpath:demo_data.sql
  liquibase:
    # Файл конфигурации Liquibase расположен по следующему пути
    change-log: classpath:liquibase/db.changelog.yaml
    # Сообщаем приложению, что Liquibase будет работать
    enabled: true
    # Данные будут сохранены в эту схему
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 3600000
    refresh: 2592000000
springdoc:
  # Отключаем отображение излишних ошибок (403, 404 и др.)
  override-with-generic-response: false
